### ISSUE TITLE
inception/inception_labels.txt is not included in the installed package by pip.

### ISSUE THREAD

**Issue by wenxichen** [learningsociety/deepmodels#1]
inception/inception_labels.txt is not included in the installed package by pip.

> $ python -m deepmodels.tf.samples.img_classifier --task 0 --data_dir /Users/wx/Desktop/deepmodels/flower_photos_small --log_dir /Users/wx/Desktop/deepmodels/flower_photos_small/results/ft/lr/01/ --batch_size 64 --opt 3 --lrate 0.005 --epochs 100
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/deepmodels/tf/samples/img_classifier.py", line 41, in <module>
    class FinetuneModel(model_zoo.NetworkDM):
  File "/usr/local/lib/python2.7/site-packages/deepmodels/tf/samples/img_classifier.py", line 46, in FinetuneModel
    incep4_model = dm_model_factory.get_dm_model(commons.ModelTypes.INCEPTION_V4)
  File "/usr/local/lib/python2.7/site-packages/deepmodels/tf/core/dm_models/dm_model_factory.py", line 20, in get_dm_model
    incep = dm_inception.InceptionDM(model_type)
  File "/usr/local/lib/python2.7/site-packages/deepmodels/tf/core/dm_models/dm_inception.py", line 62, in __init__
    self.net_label_names = self.get_label_names()
  File "/usr/local/lib/python2.7/site-packages/deepmodels/tf/core/dm_models/dm_inception.py", line 74, in get_label_names
    with open(label_fn, "r") as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/deepmodels/shared/tools/../../tf/models/inception/inception_labels.txt'

**Comment by flyfj** [comment]
that's true. thanks for the notification. you can pip install git+git://
github.com/...
it does exist in master branch but i may forget to include while packaging.
